info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  

zuul:
  prefix: /api
  routes:
    account: 
      path: /movie/**
      serviceId: movie-service
    customer: 
      path: /user/**
      serviceId: user-service          

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765
spring:
  application:
    name: gateway-server
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
