server:
  port: 8888
spring:
  application:
    name: zull-proxy
  cloud:
    consul:
      discovery:
        serviceName: zull-proxy
        register: true
      host: 127.0.0.1
      port: 8500
zuul:
  prefix: /api
  routes:
    account: 
      path: /student/**
      serviceId: consul-student-service
    customer: 
      path: /school/**
      serviceId: consul-school-service        
