server:
  port: 8082
spring:
  boot:
    admin:
      client:
        url: http://localhost:9999
  application:
    name: account-consumer
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  cloud:
    consul:
      discovery:
        register: true
        service-name: account-consumer
      host: localhost
      port: 8500
  h2: 
   console:  
       enable: true
       path: /h2 
