
server:
  port: 8504
spring:
  application:
    name: consul-student-service
  boot:
    admin:
      client:
        url: http://localhost:9999
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
  datasource:
    password: rajesh1@
    url: jdbc:mysql://localhost:3306/consul
    username: root    