server:
  port: 8503
spring:
  boot:
    admin:
      client:
        url: http://localhost:9999
      
  application:
    name: consul-school-service
  cloud:
    consul:
      discovery:
        register: true
        service-name: consul-school-service
      host: localhost
      port: 8500

          
